image: node:latest

stages:
  - lint

eslint:
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm install -g eslint
    # Configure ESLint (will read your .eslintrc file)
    - eslint --init
    # Run ESLint
    - eslint "./"
csslint:
    stage: lint
    script:
      # Install csslint
      - npm install -g csslint
      # Run CSSLint
      - csslint "./"
    allow_failure: true

